[package]
name = "ex_redis"
version = "0.1.0"
authors = ["zxc <codehackfox@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.17.0"
